name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setting JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: memberikan Perizinan gradlew
      run: chmod +x gradlew

    - name: Build debug Apk
      run: bash ./gradlew assembleDebug --warning-mode all

    - name: Upload Ke dalam Artifact
      uses: actions/upload-artifact@v1
      run: t=$(pwd | sed 's/.*\///g')
      with:
          name: test
          path: app/build/outputs/apk/debug/app-debug.apk
